### ISSUE TITLE
RuntimeVersion:: -32603: Unknown error occured: Client(RemoteFetchFailed)

### ISSUE THREAD

**Issue by amaury1093** [expenses/kusama-wasm#2]
**Repro:**
- sync to tip
- `client.rpcSend('{"method":"state_getRuntimeVersion","params":[],"id":2,"jsonrpc":"2.0"}')`

**Expected:**
- get some response

**Actual:**
```
RuntimeVersion:: -32603: Unknown error occured: Client(RemoteFetchFailed)
```

Note:
- I actually got this same error on an old (~1week) native light client, but it disappeared on latest master on polkadot. Maybe rebuilding the wasm to a more recent version would solve this problem?

**Comment by amaury1093** [comment]
Built the wasm myself, but i got when running: `panicked at 'time not implemented on wasm32-unknown-unknown', src/libstd/sys/wasm/time.rs:13:9`

**Comment by pmespresso** [comment]
^ related: https://github.com/paritytech/substrate/pull/4561

**Comment by expenses** [comment]
I'll look into this. I haven't checked all the rpc code for timing problems, so it's probably that.

**Comment by amaury1093** [comment]
Closing this, haven't seen this in the latest wasm
